// nuxt-app/components/dashboard/DashboardActions.vue
<script setup lang="ts">
import { Button } from '~/components/ui/button'
import { Theme } from '~/enums'
import { getActionsConfig } from '~/lib/theme'
import { cn } from '~/lib/utils'

interface Props {
  theme?: Theme
}

interface Emits {
  (e: 'aiFillAll'): void
  (e: 'quickFill'): void
  (e: 'clear'): void
  (e: 'refresh'): void
  (e: 'copy'): void
  (e: 'save'): void
  (e: 'sendSlack'): void
}

const props = withDefaults(defineProps<Props>(), {
  theme: Theme.DEFAULT,
})

const emit = defineEmits<Emits>()

const actionsConfig = computed(() => getActionsConfig(props.theme))

const handleQuickFill = () => {
  emit('quickFill')
}

interface ActionItem {
  config: {
    id: string
    label: string
    svgIcon?: string
    icon?: unknown
    className: string
    iconClassName?: string
  }
  onClick: () => void
  variant?: 'ghost' | 'outline' | 'default'
  showDividerAfter?: boolean
}

const actions = computed<ActionItem[]>(() => [
  { config: actionsConfig.value.aiFill, onClick: () => emit('aiFillAll') },
  { config: actionsConfig.value.quickFill, onClick: handleQuickFill },
  { config: actionsConfig.value.clear, onClick: () => emit('clear') },
  {
    config: actionsConfig.value.refresh,
    onClick: () => emit('refresh'),
    showDividerAfter: props.theme === 'pixel' || props.theme === 'coding',
  },
  { config: actionsConfig.value.copy, onClick: () => emit('copy') },
  {
    config: actionsConfig.value.save,
    onClick: () => emit('save'),
    variant: props.theme === 'default' ? 'outline' : 'ghost',
  },
  {
    config: actionsConfig.value.send,
    onClick: () => emit('sendSlack'),
    variant: props.theme === 'default' || props.theme === 'christmas' ? 'default' : 'ghost',
  },
])
</script>

<template>
  <div
    :class="cn('hidden sm:flex items-center pt-2', theme === 'default' ? 'gap-2' : 'gap-3')"
    role="toolbar"
    aria-label="Dashboard actions"
  >
    <template v-for="action in actions" :key="action.config.id">
      <Button
        :variant="(action.variant as 'ghost' | 'outline' | 'default') || 'ghost'"
        size="sm"
        :class="action.config.className"
        :aria-label="action.config.label"
        @click="action.onClick"
      >
        <img
          v-if="action.config.svgIcon"
          :src="action.config.svgIcon"
          alt=""
          :class="cn('w-4 h-4 mr-1.5', action.config.iconClassName)"
          aria-hidden="true"
        />
        <component
          :is="action.config.icon"
          v-else-if="action.config.icon"
          :class="cn('w-3.5 h-3.5 mr-1.5', action.config.iconClassName)"
        />
        <span>{{ action.config.label }}</span>
      </Button>
      <div
        v-if="action.showDividerAfter"
        :class="cn('h-6 mx-1', theme === 'coding' ? 'w-px bg-zinc-700' : 'w-0.5 bg-slate-800')"
        aria-hidden="true"
      />
    </template>
  </div>
</template>

// components/dashboard-actions.tsx
"use client"

import { Button } from "@/components/ui/button"
import { cn } from "@/lib/utils"
import { getActionsConfig } from "@/lib/theme"
import type { Theme } from "@/lib/types"

// ============================================================================
// Types
// ============================================================================

interface DashboardActionsProps {
	theme: Theme
	onAIFillAll: () => void
	onQuickFill: (status: string, action: string) => void
	onClear: () => void
	onRefresh: () => void
	onCopy: () => void
	onSave: () => void
	onSendSlack: () => void
}

interface SvgIconProps {
	src: string
	className?: string
}

// ============================================================================
// Helper Components
// ============================================================================

const SvgIcon = ({ src, className }: SvgIconProps) => (
	<img src={src} alt="" className={cn("w-4 h-4", className)} aria-hidden="true" />
)

// ============================================================================
// Action Button Component
// ============================================================================

interface ActionButtonProps {
	config: {
		id: string
		label: string
		svgIcon?: string
		icon?: React.ComponentType<{ className?: string }>
		className: string
		iconClassName?: string
	}
	onClick: () => void
	variant?: "ghost" | "outline" | "default"
	showDividerAfter?: boolean
	theme: Theme
}

const ActionButton = ({
	config,
	onClick,
	variant = "ghost",
	showDividerAfter = false,
	theme,
}: ActionButtonProps) => {
	const IconComponent = config.icon

	return (
		<>
			<Button
				variant={variant}
				size="sm"
				onClick={onClick}
				className={config.className}
				aria-label={config.label}
			>
				{config.svgIcon && (
					<SvgIcon src={config.svgIcon} className={cn("mr-1.5", config.iconClassName)} />
				)}
				{IconComponent && (
					<IconComponent className={cn("w-3.5 h-3.5 mr-1.5", config.iconClassName)} />
				)}
				<span>{config.label}</span>
			</Button>
			{showDividerAfter && (
				<div
					className={cn(
						"h-6 mx-1",
						theme === "coding" ? "w-px bg-zinc-700" : "w-0.5 bg-slate-800"
					)}
					aria-hidden="true"
				/>
			)}
		</>
	)
}

// ============================================================================
// Main Component
// ============================================================================

export const DashboardActions = ({
	theme,
	onAIFillAll,
	onQuickFill,
	onClear,
	onRefresh,
	onCopy,
	onSave,
	onSendSlack,
}: DashboardActionsProps) => {
	const actionsConfig = getActionsConfig(theme)

	const handleQuickFill = () => {
		onQuickFill("Pending", "Will check tomorrow")
	}

	const actions = [
		{ config: actionsConfig.aiFill, onClick: onAIFillAll },
		{ config: actionsConfig.quickFill, onClick: handleQuickFill },
		{ config: actionsConfig.clear, onClick: onClear },
		{ config: actionsConfig.refresh, onClick: onRefresh, showDividerAfter: theme === "pixel" || theme === "coding" },
		{ config: actionsConfig.copy, onClick: onCopy },
		{ config: actionsConfig.save, onClick: onSave, variant: theme === "default" ? "outline" as const : "ghost" as const },
		{ config: actionsConfig.send, onClick: onSendSlack, variant: theme === "default" || theme === "christmas" ? "default" as const : "ghost" as const },
	]

	return (
		<div
			className={cn(
				"hidden sm:flex items-center pt-2",
				theme === "default" ? "gap-2" : "gap-3"
			)}
			role="toolbar"
			aria-label="Dashboard actions"
		>
			{actions.map(({ config, onClick, variant = "ghost", showDividerAfter = false }) => (
				<ActionButton
					key={config.id}
					config={config}
					onClick={onClick}
					variant={variant}
					showDividerAfter={showDividerAfter}
					theme={theme}
				/>
			))}
		</div>
	)
}
