// nuxt-app/components/feedback/FeedbackForm.vue
<script setup lang="ts">
import { Send, Loader2 } from 'lucide-vue-next'
import { Button } from '~/components/ui/button'
import { FeedbackType } from '~/enums'
import FeedbackTypeSelector from './FeedbackTypeSelector.vue'
import FeedbackDetailsCard from './FeedbackDetailsCard.vue'
import AnonymousNotice from './AnonymousNotice.vue'

interface Emits {
  (e: 'success'): void
}

const emit = defineEmits<Emits>()
const { $toast } = useNuxtApp()

const selectedType = ref<FeedbackType | null>(null)
const title = ref('')
const description = ref('')
const isSubmitting = ref(false)

const isValid = computed(() => selectedType.value && title.value.trim() && description.value.trim())

const handleSubmit = async () => {
  if (!selectedType.value || !title.value.trim() || !description.value.trim()) {
    $toast?.error('Please fill in all required fields')
    return
  }

  isSubmitting.value = true

  try {
    await $fetch('/api/feedback', {
      method: 'POST',
      body: {
        type: selectedType.value,
        title: title.value.trim(),
        description: description.value.trim(),
      },
    })

    $toast?.success('Thank you for your feedback!')
    emit('success')
  } catch (e) {
    $toast?.error((e as Error).message || 'Failed to submit feedback')
  } finally {
    isSubmitting.value = false
  }
}
</script>

<template>
  <form @submit.prevent="handleSubmit">
    <FeedbackTypeSelector
      :selected-type="selectedType"
      @select-type="selectedType = $event"
    />
    <FeedbackDetailsCard
      v-model:title="title"
      v-model:description="description"
      :selected-type="selectedType"
    />
    <AnonymousNotice />
    <Button
      type="submit"
      size="lg"
      class="w-full"
      :disabled="!isValid || isSubmitting"
    >
      <template v-if="isSubmitting">
        <Loader2 class="w-4 h-4 mr-2 animate-spin" />
        Submitting...
      </template>
      <template v-else>
        <Send class="w-4 h-4 mr-2" />
        Submit Feedback
      </template>
    </Button>
  </form>
</template>

// components/feedback/feedback-form.tsx
"use client"

import { useState } from "react"
import { toast } from "sonner"
import { Send, Loader2 } from "lucide-react"
import { Button } from "@/components/ui/button"
import { trpc } from "@/components/trpc-provider"
import { FeedbackType } from "@/enums"
import { FeedbackTypeSelector } from "./feedback-type-selector"
import { FeedbackDetailsCard } from "./feedback-details-card"
import { AnonymousNotice } from "./anonymous-notice"

interface FeedbackFormProps {
  onSuccess: () => void
}

export function FeedbackForm({ onSuccess }: FeedbackFormProps) {
  const [selectedType, setSelectedType] = useState<FeedbackType | null>(null)
  const [title, setTitle] = useState("")
  const [description, setDescription] = useState("")
  const [isSubmitting, setIsSubmitting] = useState(false)

  const createFeedbackMutation = trpc.feedback.create.useMutation({
    onSuccess: () => {
      onSuccess()
      toast.success("Thank you for your feedback!")
    },
    onError: (error) => {
      toast.error(error.message || "Failed to submit feedback")
    },
  })

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()

    if (!selectedType || !title.trim() || !description.trim()) {
      toast.error("Please fill in all required fields")
      return
    }

    setIsSubmitting(true)

    try {
      await createFeedbackMutation.mutateAsync({
        type: selectedType,
        title: title.trim(),
        description: description.trim(),
      })
    } finally {
      setIsSubmitting(false)
    }
  }

  const isValid = selectedType && title.trim() && description.trim()

  return (
    <form onSubmit={handleSubmit}>
      <FeedbackTypeSelector selectedType={selectedType} onSelectType={setSelectedType} />
      <FeedbackDetailsCard
        selectedType={selectedType}
        title={title}
        description={description}
        onTitleChange={setTitle}
        onDescriptionChange={setDescription}
      />
      <AnonymousNotice />
      <Button type="submit" size="lg" className="w-full" disabled={!isValid || isSubmitting}>
        {isSubmitting ? (
          <>
            <Loader2 className="w-4 h-4 mr-2 animate-spin" />
            Submitting...
          </>
        ) : (
          <>
            <Send className="w-4 h-4 mr-2" />
            Submit Feedback
          </>
        )}
      </Button>
    </form>
  )
}
